### ISSUE TITLE
NextJS tutorial: pages and CSS

### ISSUE THREAD

**Issue by Skidle** [metisova/sturdy-lamp#15]
## Problem

It's good to read the docs first before diving into a new framework.

Let's learn basics of NextJS, how it's different from React, what are pages and how we can style them.

## Solution suggestion

Follow this tutorial https://nextjs.org/learn/basics/create-nextjs-app, lessons `Create a Next.js App`, `Navigate Between Pages` and selected parts of `Assets, Metadata, and CSS`

![image](https://github.com/metisova/sturdy-lamp/assets/22978238/6369926d-2cf7-47b2-9dce-7fb15f513364)

## Acceptance criteria

Successfully completed a basic NextJS tutorial.

## Learning outcome

Learned how to create a new page, edit it and style it in NextJS ✔️

**Comment by metisova** [comment]
Tutorial is completes  (lessons: `Create a Next.js App`, `Navigate Between Pages` and selected parts of `Assets, Metadata, and CSS`). 

However, I'd also to complete the whole `Assets, Metadata, and CSS` section for better understanding :)
